CREATE DATABASE parque_Atraccines; --Le puse este nombre porque habla sobre entradas y me parecio el mas acertado.

USE parque_Atracciones;

--No me han especificado los valores de cada atributo entonces lo puse con NVARCHAR y con un tamaño aceptable.
CREATE TABLE RECINTO(
	codRECINTO NVARCHAR (255) NOT NULL, 
	nomRECINTO NVARCHAR (255) NOT NULL,
	dirRECINTO NVARCHAR (255) NOT NULL,
	ciuRECINTO NVARCHAR (255) NOT NULL,
	telRECINTO NVARCHAR (255) NOT NULL,
	horRECINTO TIME NOT NULL,

	CONSTRAINT pk_RECINTO_codRECINTO PRIMARY KEY (codRECINTO)
);

CREATE TABLE ESPECTACULO(
	codESPECTACULO NVARCHAR (255) NOT NULL,
	nomESPECTACULO NVARCHAR (255) NOT NULL,
	tipoESPECTACULO NVARCHAR (255) NOT NULL,
	fechainicioESPECTACULO DATE NOT NULL,
	fechafinalESPECTACULO DATE NOT NULL,
	interpreteESPECTACULO NVARCHAR NOT NULL,
	codRECINTO NVARCHAR (255) NOT NULL,

	CONSTRAINT pk_ESPECTACULO_codESPECTACULO PRIMARY KEY (codESPECTACULO),
	CONSTRAINT fk_ESPECTAVULO_codRECINTO FOREIGN KEY (codRECINTO) REFERENCES RECINTO(codRECINTO),
);

CREATE TABLE ASIENTO(
	numASIENTO INT IDENTITY (1,1) NOT NULL,
	filASIENTO INT NOT NULL,
	codRECINTO NVARCHAR (255) NOT NULL,

	CONSTRAINT pk_ASIENTO PRIMARY KEY (numASIENTO, filASIENTO),
	CONSTRAINT fk_ASIENTO_codRECINTO FOREIGN KEY (codRECINTO) REFERENCES RECINTO(codRECINTO),
	CONSTRAINT ch_ASIENTO_numASIENTO CHECK (numASIENTO >= 0),
);

ALTER TABLE ASIENTO
ADD CONSTRAINT df_ASIENTO_filASIENTO
DEFAULT 0 FOR filASIENTO;

CREATE TABLE REPRESENTACION(
	codREPRESENTACION NVARCHAR (255) NOT NULL,
	codESPECTACULO NVARCHAR (255) NOT NULL,
	fechaREPRESENTACION DATE NOT NULL,
	horaREPRESENTACION TIME NOT NULL,

	CONSTRAINT pk_REPRESENTACION_codREPRESENTACION PRIMARY KEY (codREPRESENTACION),
	CONSTRAINT fk_REPRESENTACION_codESPECTACULO FOREIGN KEY (codESPECTACULO) REFERENCES ESPECTACULO(codESPECTACULO)
);

CREATE TABLE PRECIO_REPRESENTACION(
	codESPECTACULO NVARCHAR (255) NOT NULL,
	codREPRESENTACION NVARCHAR (255) NOT NULL,
	pvpESPECTACULO INT NOT NULL,

	CONSTRAINT pk_PRECIO_REPRESENTACION PRIMARY KEY (codESPECTACULO, codREPRESENTACION),
	CONSTRAINT fk_PRECIO_REPRESENTACION_codESPECTACULO FOREIGN KEY (codESPECTACULO) REFERENCES ESPECTACULO(codESPECTACULO),
	CONSTRAINT fk_PRECIO_REPRESENTACION_codREPRESENTACION FOREIGN KEY (codREPRESENTACION) REFERENCES REPRESENTACION(codREPRESENTACION),
);

CREATE TABLE ESPECTADOR(
	dniESPECTADOR NVARCHAR (255) NOT NULL,
	nomESPECTADOR NVARCHAR (255) NOT NULL,
	dirESPECTADOR NVARCHAR (255) NOT NULL,
	telESPECTADOR NVARCHAR (255),
	ciuESPECTADOR NVARCHAR (255),
	numeroTarjeta INT,

	CONSTRAINT pk_ESPECTADOR_dniESPECTADOR PRIMARY KEY (dniESPECTADOR),
	CONSTRAINT uq_ESPECTADOR_numeroTarjeta UNIQUE (numeroTarjeta)
);

CREATE TABLE ENTRADA(
	codENTRADA NVARCHAR (255) NOT NULL,
	codREPRESENTACION NVARCHAR (255) NOT NULL,
	codRECINTO NVARCHAR (255) NOT NULL,
	numASIENTO INT NOT NULL,
	filASIENTO INT NOT NULL,
	dniESPECTADOR NVARCHAR (255) NOT NULL,

	CONSTRAINT pk_ENTRADA_codENTRADA PRIMARY KEY (codENTRADA),
	CONSTRAINT fk_ENTRADA_codREPRESENTACION FOREIGN KEY (codREPRESENTACION) REFERENCES REPRESENTACION(codREPRESENTACION),
	CONSTRAINT fk_ENTRADA_codRECINTO FOREIGN KEY (codRECINTO) REFERENCES RECINTO(codRECINTO),
	CONSTRAINT fk_ENTRADA_numASIENTO_filASIENTO FOREIGN KEY (numASIENTO, filASIENTO) REFERENCES ASIENTO(numASIENTO, filASIENTO),
	CONSTRAINT fk_ENTRADA_dniESPECTADOR FOREIGN KEY (dniESPECTADOR) REFERENCES ESPECTADOR(dniESPECTADOR),
);

--APARTADO_01
CREATE LOGIN adminEntradasLogin
WITH PASSWORD = 'Constraseña9';

CREATE USER adminEntradas
FOR LOGIN adminEntradasLogin;

--APARTADO_02
CREATE USER consultaPublica
WITHOUT LOGIN;

--APARTADO_03
GRANT SELECT
ON RECINTO
TO consultaPublica;

GRANT SELECT
ON ESPECTACULO
TO consultaPublica;

GRANT SELECT
ON REPRESENTACION
TO consultaPublica;

--APARTADO_04
CREATE LOGIN gestorEspectaculosLogin
WITH PASSWORD = 'Contraseña_segura9';

CREATE USER gestorEspectaculos
FOR LOGIN gestorEspectaculosLogin;

GRANT SELECT, INSERT, UPDATE
ON ESPECTACULO
TO gestorEspectaculos;

DENY DELETE
ON ESPECTACULO
TO gestorEspectaculos;

--APARTADO_05
CREATE LOGIN gestorRecintosLogin
WITH PASSWORD = 'Contraseña_ultra_segura9';

CREATE USER gestorRecintos
FOR LOGIN gestorRecintosLogin;

GRANT INSERT, UPDATE, DELETE
ON RECINTO 
TO gestorRecintos;

DENY SELECT
ON ESPECTADOR
TO gestorRecintos;

--APARTADO_06
CREATE LOGIN usuarioEspectadorLogin
WITH PASSWORD = 'Contraseña_ultra_mega_segura9';

CREATE USER usuarioEspectador
FOR LOGIN usuarioEspectadorLogin;

GRANT SELECT
ON ESPECTACULO
TO usuarioEspectador;

GRANT SELECT
ON REPRESENTACION
TO usuarioEspectador;

GRANT SELECT
ON PRECIO_REPRESENTACION
TO usuarioEspectador;

DENY UPDATE
ON ESPECTACULO
TO usuarioEspectador;

DENY UPDATE
ON REPRESENTACION
TO usuarioEspectador;

DENY UPDATE
ON PRECIO_REPRESENTACION
TO usuarioEspectador;

--APARTADO_07

GRANT INSERT, UPDATE, DELETE
ON ENTRADA
TO adminEntradas
WITH GRANT OPTION;

--APARTADO_08
REVOKE UPDATE
ON ESPECTACULO
TO gestorEspectaculos;

--APARTADO_09
DENY ALL
ON ESPECTADOR
TO consultaPublica;

--APARTADO_10
ALTER USER gestorRecintos 
WITH NAME = coordinadorRecintos;

ALTER LOGIN gestorRecintosLogin
WITH NAME = coordinadorRecintosLogin;

--APARTADO_11
GRANT ALL
ON REPRESENTACION
TO adminEntradas;

--APARTADO_12
DROP USER consultaPublica;